language: java
os: linux
dist: bionic
install: mvn -Ptravis -DskipTests=true -nsu -B install
script:
  - mvn -Ptravis ${JACOCO} -nsu -B test
  - find $HOME/.m2/repository/com/google/zxing -path "*SNAPSHOT/*" -delete
  - find $HOME/.m2/repository/com/google/zxing -name "*SNAPSHOT" -type d -delete
jobs:
 include:
   - jdk: openjdk8
     env:
       - JACOCO=-Pjacoco
       - ANDROID_HOME=$HOME/android-sdk-linux
     before_install: if [ ! -d $HOME/android-sdk-linux/platforms ]; then curl -s https://storage.googleapis.com/zxing-build/android-sdk-linux.tar.bz2 | bunzip2 | tar xf - -C $HOME; else ls -l $HOME/android-sdk-linux; fi
   - jdk: openjdk11
   - jdk: openjdk14
   # - jdk: openjdk11
   #   arch: arm64
   #   before_install:
   #     - curl -O https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
   #     - tar xzf apache-maven-3.6.3-bin.tar.gz
   #     - export PATH=`pwd`/apache-maven-3.6.3/bin:$PATH
   #     - mvn -v
cache:
  directories:
    - $HOME/.m2
    - $HOME/android-sdk-linux
git:
  quiet: true
  depth: 10
after_success: if [ -n "$JACOCO" ]; then bash <(curl -s https://codecov.io/bash); fi

# The Android SDK package android-sdk-linux.tar.bz2 above is built roughly like so:
#
# Download Command Line tools for Linux from https://developer.android.com/studio#downloads
#
# mkdir android-sdk-linux; cd android-sdk-linux
# mv /path/to/sdk-tools-linux-4333796.zip .
# unzip *.zip; rm *.zip
#
# # Or different, more recent versions; see sdkmanager --list
# ./tools/bin/sdkmanager "platforms;android-22" "build-tools;28.0.2"
# # Accept license
#
# ./tools/bin/sdkmanager --update
# # Accept license
#
# cp tools/source.properties ..
#
# ./tools/bin/sdkmanager --uninstall tools
#
# mkdir tools; mv ../source.properties tools
#
# cd ..
# tar cf - android-sdk-linux | bzip2 -9 > android-sdk-linux.tar.bz2
